### ISSUE TITLE
Migration generator is broken on Rails 5?

### ISSUE THREAD

**Issue by Sprachprofi** [olegantonyan/translateable#12]
When I type `rails g translateable:migration petition addressee`  (with or without 'en' as additional parameter), I get
```
(erb):16:in `migration_template': undefined method `index_exists?' for #<Transla
teable::MigrationGenerator:0xc10ad18> (NoMethodError)
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/2.3.0/erb.rb:864:in `eval'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/2.3.0/erb.rb:864:in `result'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.1.0
/lib/rails/generators/migration.rb:64:in `block in migration_template'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.20.3/li
b/thor/actions/create_file.rb:53:in `render'
```

**Comment by olegantonyan** [comment]
Will check it. Thanks for the report

**Comment by olegantonyan** [comment]
@Sprachprofi  fixed (version 0.2.0)

**Comment by Sprachprofi** [comment]
Thanks. I'm even using the plugin on Rails 6 with Postgresql 13 now, works fine :)
